sudo: required
language: ruby
rvm: 2.2
node_js: "0.10"
before_script:
  - gem install awesome_bot
  - sudo pip install json-spec
jobs:
  include:
    - stage: "Test"
      script: awesome_bot contents.json -w AERecord,theswiftwebdeveloper,bluemix,swiftplayground,awesome-for-swift-cheatsheet
      script: json validate --schema-file=.github/schema.json --document-file=contents.json
    - stage: "Before Deploy"
      script: ruby .github/convert.rb
      script: node .github/upgradeDb.js
      if: branch = master
    - stage: "Deploy"
      script: ./.github/deploy.sh
      if: branch = master
